spring:
  application:
    name: recipe-app-backend
# custom properties
# Ollama settings
ollama:
  base-url: http://localhost:11434
  model-name: gemma3:4b
# Qdrant settings
qdrant:
  host: localhost
  #qdrant.port=6333
  grpc-port: 6334
  collection.name: recipes
embedding:
  model:
    name: nomic-embed-text